### ISSUE TITLE
Aplikacja serwerowa

### ISSUE THREAD

**Issue by sbajdas** [DSMMM/Battleships#18]
Przyjmowanie połączeń w sockety, organizacja czatu między uzytkownikami
Wyświetlenie wiadomości powitalnej użytkownikowi.
Dodanie zawsze przechodzącego testu by Jenkins miał nad czym pracować

**Comment by mkrupnik** [comment]
Socket clienta uruchumiony na serwerze i porcie 8189: 
Socket echoSocket = new Socket("vps624409.ovh.net", 8189);

Testy dodane, zawsze przechodzą: assertTrue(true);

**Comment by mkrupnik** [comment]
chat gotowy, sprawdzony, demo zweryfikuje
